// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.CANSparkMax.IdleMode;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private CANSparkMax sparkMAX1;
private CANSparkMax sparkMAX2;
private MotorControllerGroup rightMotorController;
private CANSparkMax sparkMAX3;
private CANSparkMax sparkMAX4;
private MotorControllerGroup leftMotorController;
private DifferentialDrive differentialDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public DriveTrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
sparkMAX1 = new CANSparkMax(1, MotorType.kBrushless);
 
 sparkMAX1.restoreFactoryDefaults();  
sparkMAX1.setInverted(true);
sparkMAX1.setIdleMode(IdleMode.kCoast);
  

sparkMAX2 = new CANSparkMax(2, MotorType.kBrushless);
 
 sparkMAX2.restoreFactoryDefaults();  
sparkMAX2.setInverted(true);
sparkMAX2.setIdleMode(IdleMode.kCoast);
  

rightMotorController = new MotorControllerGroup(sparkMAX1, sparkMAX2  );
 addChild("RightMotorController",rightMotorController);
 

sparkMAX3 = new CANSparkMax(3, MotorType.kBrushless);
 
 sparkMAX3.restoreFactoryDefaults();  
sparkMAX3.setInverted(false);
sparkMAX3.setIdleMode(IdleMode.kCoast);
  

sparkMAX4 = new CANSparkMax(4, MotorType.kBrushless);
 
 sparkMAX4.restoreFactoryDefaults();  
sparkMAX4.setInverted(false);
sparkMAX4.setIdleMode(IdleMode.kCoast);
  

leftMotorController = new MotorControllerGroup(sparkMAX3, sparkMAX4  );
 addChild("LeftMotorController",leftMotorController);
 

differentialDrive1 = new DifferentialDrive(leftMotorController, rightMotorController);
 addChild("Differential Drive 1",differentialDrive1);
 differentialDrive1.setSafetyEnabled(true);
differentialDrive1.setExpiration(0.1);
differentialDrive1.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
        public void my_drivercade(double xSpeed, double zRotation) {
            differentialDrive1.arcadeDrive(xSpeed, zRotation);
}
    //Add an encoder
    //Supper Coder
}

